workflows:
  ios-workflow:
    name: iOS Build - Pawtech
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      ios_signing:
        distribution_type: development        # or ad_hoc / app_store
        bundle_identifier: com.yourcompany.pawtech
    scripts:
      - name: Flutter deps
        script: |
          flutter --version
          flutter pub get
      - name: Build signed IPA
        script: |
          flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      email:
        recipients:
          - somarious2@gmail.com  # Change to your email
        notify:
          success: true
          failure: true

  # Optional: Android workflow for testing
  android-workflow:
    name: Android Build - Pawtech
    max_build_duration: 60
    environment:
      flutter: stable
      android_signing:
        - keystore_reference
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Set up Flutter
        script: |
          flutter doctor
          flutter --version
      
      - name: Get Flutter dependencies
        script: |
          flutter pub get
      
      - name: Build Android APK
        script: |
          flutter build apk --release
    
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    
    publishing:
      email:
        recipients:
          - somarious2@gmail.com # Change to your email
        notify:
          success: true
          failure: true

  ios-unsigned-for-altstore:
    name: iOS device build (unsigned, for AltStore)
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Deps
        script: |
          flutter --version
          flutter pub get
      - name: Build iOS (device, no code signing)
        script: |
          export IPHONEOS_DEPLOYMENT_TARGET=14.0
          flutter build ios --release --no-codesign
      - name: Package unsigned IPA
        script: |
          cd build/ios/iphoneos
          rm -rf Payload && mkdir Payload
          cp -R Runner.app Payload/
          zip -qry Runner-unsigned.ipa Payload
    artifacts:
      - build/ios/iphoneos/Runner-unsigned.ipa
