workflows:
  ios-workflow:
    name: iOS Build - Pawtech
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Flutter deps
        script: |
          flutter --version
          flutter pub get

      - name: Ensure Pods use iOS 14 and update repos
        script: |
          cd ios
          # Force Podfile to use iOS 14
          sed -i '' 's/platform :ios, .*/platform :ios, "14.0"/g' Podfile || echo 'platform :ios, "14.0"' >> Podfile
          
          # Force Xcode project to use iOS 14
          find . -name "project.pbxproj" -print0 | xargs -0 sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = [0-9]\{1,2\}\.[0-9]\{1,2\}/IPHONEOS_DEPLOYMENT_TARGET = 14.0/g'

          # Update pods
          pod repo update
          pod install
          cd ..

      - name: Build iOS app (unsigned)
        script: |
          export CODE_SIGNING_ALLOWED=NO
          export CODE_SIGNING_REQUIRED=NO
          export CODE_SIGN_IDENTITY=""
          flutter build ios --release --no-codesign

      - name: Package unsigned IPA
        script: |
          cd build/ios/iphoneos
          rm -rf Payload && mkdir Payload
          cp -R Runner.app Payload/
          zip -qry Runner-unsigned.ipa Payload

    artifacts:
      - build/ios/iphoneos/Runner-unsigned.ipa
      - /tmp/xcodebuild_logs/*.log
    
    publishing:
      email:
        recipients:
          - somarious2@gmail.com
        notify:
          success: true
          failure: true

  # Optional: Android workflow for testing
  android-workflow:
    name: Android Build - Pawtech
    max_build_duration: 60
    environment:
      flutter: stable
      android_signing:
        - keystore_reference
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Set up Flutter
        script: |
          flutter doctor
          flutter --version
      
      - name: Get Flutter dependencies
        script: |
          flutter pub get
      
      - name: Build Android APK
        script: |
          flutter build apk --release
    
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    
    publishing:
      email:
        recipients:
          - somarious2@gmail.com
        notify:
          success: true
          failure: true
