workflows:
  ios-unsigned-for-altstore:
    name: iOS Build (unsigned, for AltStore / manual signing)
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Flutter deps
        script: |
          flutter --version
          flutter pub get
      - name: Build iOS (unsigned, no code signing)
        script: |
          export CODE_SIGNING_ALLOWED=NO
          export CODE_SIGNING_REQUIRED=NO
          export CODE_SIGN_IDENTITY=""
          flutter build ios --release --no-codesign
      - name: Package unsigned IPA
        script: |
          cd build/ios/iphoneos
          rm -rf Payload && mkdir Payload
          cp -R Runner.app Payload/
          zip -qry Runner-unsigned.ipa Payload
    artifacts:
      - build/ios/iphoneos/Runner-unsigned.ipa
