name: pawtech
description: "A new Flutter module project."

version: 1.0.0+1

environment:
  sdk: ^3.5.0  # Changed from ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  
  # Use compatible Firebase versions that work with iOS 15.0
  provider: ^6.1.2
  firebase_core: ^3.1.0        # Compatible version
  firebase_auth: ^5.1.0        # Compatible version
  cloud_firestore: ^5.0.0      # Compatible version
  firebase_database: ^11.0.0   # This version exists
  firebase_messaging: ^15.0.0  # Compatible version
  
  # Other dependencies stay the same
  google_maps_flutter: ^2.9.0
  geolocator: ^13.0.1
  permission_handler: ^11.3.1
  flutter_local_notifications: ^17.2.3
  image_picker: ^1.1.2
  qr_flutter: ^4.1.0
  intl: ^0.19.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0  # Changed from ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  module:
    androidX: true
    androidPackage: com.example.pawtech
    iosBundleIdentifier: com.example.pawtech
