on:
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter pub get
        run: flutter pub get

      - name: Build iOS (device, unsigned)
        run: flutter build ios --release --no-codesign

      - name: Package unsigned IPA
        run: |
          cd build/ios/iphoneos
          mkdir Payload
          cp -r Runner.app Payload/
          zip -r ../../../pawtech-unsigned.ipa Payload/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pawtech-unsigned-ipa
          path: pawtech-unsigned.ipa
